# Generated by Django 6.0.2 on 2026-02-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('medical_history', models.TextField(blank=True)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('medical_status', models.CharField(choices=[('checked_in', 'Checked In'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('observation', 'Under Observation')], default='checked_in', max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
